export const SET_MENU_VISIBILITY = 'SET_MENU_VISIBILITY'
export const TOGGLE_MENU_VISIBILITY = 'TOGGLE_MENU_VISIBILITY'

export const SET_TITLE = 'SET_TITLE'
export const SET_AUTH_STATE = 'SET_AUTH_STATE'
